export default[
  {
    "_id": "A101",
    "title": "Propulsion Assignment",
    "course": "RS101",
    "description": "Analyze the propulsion system design and submit your findings in a report.",
    "points": 100,
    "group": "Assignments",
    "displayGrade": "Percentage",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-11-15",
    "availableFrom": "2024-11-01",
    "availableUntil": "2024-11-20"
  },
  {
    "_id": "A102",
    "title": "Combustion Analysis",
    "course": "RS101",
    "description": "Evaluate combustion chamber performance under varying conditions.",
    "points": 100,
    "group": "Assignments",
    "displayGrade": "Percentage",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-11-22",
    "availableFrom": "2024-11-10",
    "availableUntil": "2024-11-25"
  },
  {
    "_id": "A103",
    "title": "Nozzle Design Project",
    "course": "RS101",
    "description": "Design a converging-diverging nozzle and simulate its efficiency.",
    "points": 150,
    "group": "Project",
    "displayGrade": "Points Earned",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-12-01",
    "availableFrom": "2024-11-15",
    "availableUntil": "2024-12-05"
  },
  {
    "_id": "A201",
    "title": "Aerodynamics Quiz",
    "course": "RS102",
    "description": "Timed quiz on aerodynamic principles and flow regimes.",
    "points": 50,
    "group": "Quizzes",
    "displayGrade": "Percentage",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-10-10",
    "availableFrom": "2024-10-01",
    "availableUntil": "2024-10-12"
  },
  {
    "_id": "A202",
    "title": "Flow Analysis",
    "course": "RS102",
    "description": "Submit a CFD simulation and flow visualization analysis report.",
    "points": 100,
    "group": "Assignments",
    "displayGrade": "Points Earned",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-10-20",
    "availableFrom": "2024-10-05",
    "availableUntil": "2024-10-25"
  },
  {
    "_id": "A203",
    "title": "Heating Analysis",
    "course": "RS102",
    "description": "Perform a heat transfer analysis and compare with theoretical values.",
    "points": 100,
    "group": "Assignments",
    "displayGrade": "Percentage",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-10-30",
    "availableFrom": "2024-10-15",
    "availableUntil": "2024-11-01"
  },
  {
    "_id": "A301",
    "title": "Structural Design Task",
    "course": "RS103",
    "description": "Design and evaluate the structural integrity of aerospace components.",
    "points": 120,
    "group": "Assignments",
    "displayGrade": "Points Earned",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-12-10",
    "availableFrom": "2024-11-25",
    "availableUntil": "2024-12-15"
  },
  {
    "_id": "A302",
    "title": "Orbital Calculations",
    "course": "RS103",
    "description": "Calculate satellite orbital parameters and mission timelines.",
    "points": 100,
    "group": "Assignments",
    "displayGrade": "Percentage",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-12-17",
    "availableFrom": "2024-12-01",
    "availableUntil": "2024-12-20"
  },
  {
    "_id": "A303",
    "title": "Systems Engineering Exam",
    "course": "RS103",
    "description": "Comprehensive exam covering systems engineering fundamentals.",
    "points": 200,
    "group": "Exams",
    "displayGrade": "Percentage",
    "submissionType": "Online",
    "assignTo": "Everyone",
    "dueDate": "2024-12-22",
    "availableFrom": "2024-12-15",
    "availableUntil": "2024-12-25"
  }
]
